# This is a 'configauration' file for generating the CV.
# Modify this file properly(!) to get your desired result.

# Author: Indrajit Ghosh
# Created On: Dec 26, 2022
    
    
# Personal Info
FIRST_NAME : Debjit
FAMILY_NAME : Ghosh
ADDRESS_LINE_1 : North 24 Parganas
ADDRESS_LINE_2 : West Bengal 743247, India
MOBILE : (+91) 8609655696
EMAIL : debjitghosh404@gmail.com
PHOTO_FILENAME :

# CV Settings
THEME : classic  # available - 'classic' (default), 'casual', 'oldstyle' and 'banking'
COLOR : black    # available - 'black' (default), 'orange', 'green', 'red', 'purple', 'grey' and 'blue'
FONT_SIZE : 11  # available - 10, 11, or 12;
PAPER_SIZE : a4paper  # available - a4paper, letterpaper, a5paper, legalpaper, executivepaper or landscape
FONT_FAMILY : sans # available - sans or roman
PHOTO_HEIGHT : 70
PHOTO_THICKNESS : 0.9

# Education
EDUCATION:
  - name : Madhyamik
    years : 2014
    institution : Dakshin Chatra High School
    country : India
    grade : Percentage 77.28
    description : West Bengal Board Of Secondary Education

  - name : Higher Secondary
    years : 2016
    institution : Dakshin Chatra High School
    country : India
    grade : Percentage 70.8
    description : West Bengal Council Of Higher Secondary Education

  - name : Diploma In Civil Engineering
    years : 2016--2019
    institution : Ramakrishna Mission Shilpapitha
    country : India
    grade : Percentage 78.2
    description : West Bengal State council Of Technical \& Vocational Education \& Skill Development

  - name : B.TECH In Civil Engineering
    years : 2020--present
    institution : Meghnad Saha Institute Of Technology
    country : India
    grade : 6th SEM 89.2
    description : Maulana Abul Kamal Umiversity Of Technology


# Internships
INTERNSHIPS:
  - name : DESIGN CAPACITY OF 200KL OVER HEAD WATER TANK FOR 14M R.C.C. STAGING
    years : Aug--Sept, 2022 
    institution : Ionexchange India LTD.
    description : 
      -  "" # a line which contains the key ':' must be put inside a double quotation "..."
      -  ""


# Projects
PROJECTS:
  - name : Summer Project Work
    years : 2019--2020 
    institution : Indian Statistical Institute, Kolkata
    description : 
      -  "Title: What is Mathematics?" # a line which contains the key ':' must be put inside a double quotation "..."
      -  "Instructor: Dr. Malay Ghosh"

  - name : Semester Project
    years : 2019--2020 
    institution : Indian Statistical Bangalore, Kolkata
    description : 
      -  "Title: Fine Analysis of Molecules" # a line which contains the key ':' must be put inside a double quotation "..."
      -  "Instructor: Dr. Soumyashant Nayak"
  

# Skills
PROGRAMMING_LANGUAGE :
DESIGN : AUtocad
ANALYSIS : Staad Pro
ENVIRONMENT : 
OS : MacOS and Windows

# Languages
BENGALI : Native Speaker
ENGLISH : Fluent
HINDI : Speak and understand

# Extra Curricular Activities
EXTRA_ACTIVITIES :
  - Swimming
  - Singing

    
    
